### ISSUE TITLE
rsIDs required?

### ISSUE THREAD

**Issue by jdarias93** [brielin/Popcorn#11]
Dear Popcorn Team,
I am running into an issue where POPCORN doesn’t recognize any of the SNPs in our summary files.
Do the summary SNP input files need to have an rsIDs column?
Here is the error log:
```
Popcorn version 1.0
(C) 2015-2019 Brielin C Brown
University of California, Berkeley
GNU General Public License v3

Invoking command: python ~/Josh/Popcorn/popcorn/popcorn.py fit \
--sfile1 <SummaryFile>
--cfile ~/Josh/Popcorn/popcorn/test/EUR_EAS_all_gen_imp_EDIT.cscore POPCORN_imp_EDIT.out

Beginning analysis at Wed Jan 29 16:10:17 2020
Analyzing a single trait in one population
24094453 SNPs detected in input.
0 SNPs remaining after merging with score file.
0 SNPs remaining after filtering on AF and self-compliment SNPs.
Traceback (most recent call last):
  File "/net/giant-glgc/disk1/incoming/sftp/GIANT/Cleaning_and_QC/Josh/Popcorn/popcorn/popcorn.py", line 248, in <module>
    main()
  File "/net/giant-glgc/disk1/incoming/sftp/GIANT/Cleaning_and_QC/Josh/Popcorn/popcorn/popcorn.py", line 182, in main
    res = fit.fit_h(data.data,args,M=M)
  File "/net/giant-glgc/disk1/incoming/sftp/GIANT/Cleaning_and_QC/Josh/Popcorn/popcorn/fit.py", line 76, in __init__
    self.h_res, self.sy, self.ll = self.__call__(data,args)
  File "/net/giant-glgc/disk1/incoming/sftp/GIANT/Cleaning_and_QC/Josh/Popcorn/popcorn/fit.py", line 141, in __call__
    wls = sm.WLS(Y, X, W)
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/regression/linear_model.py", line 526, in __init__
    weights=weights, hasconst=hasconst, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/regression/linear_model.py", line 95, in __init__
    super(RegressionModel, self).__init__(endog, exog, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/base/model.py", line 212, in __init__
    super(LikelihoodModel, self).__init__(endog, exog, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/base/model.py", line 63, in __init__
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/base/model.py", line 88, in _handle_data
    data = handle_data(endog, exog, missing, hasconst, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/base/data.py", line 630, in handle_data
    **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/base/data.py", line 79, in __init__
    self._handle_constant(hasconst)
  File "/usr/local/lib/python2.7/dist-packages/statsmodels/base/data.py", line 131, in _handle_constant
    const_idx = np.where(self.exog.ptp(axis=0) == 0)[0].squeeze()
  File "/net/wonderland/home/sberndt/.local/lib/python2.7/site-packages/numpy/core/_methods.py", line 153, in _ptp
    umr_maximum(a, axis, None, out, keepdims),
ValueError: zero-size array to reduction operation maximum which has no identity
```
Please let me know if you need any more information or have any further questions.
Thank you in advance,
Josh

**Comment by brielin** [comment]
It should require either an rsid column or chr and pos columns, the score file should also have chr and pos columns. It looks like for your files they aren't matching up for some reason, probably a simple formatting issue.

**Comment by zhangchuyi** [comment]
I have also met this problem and I solved it by changing the alleles info from lowercase to uppercase.
