### ISSUE TITLE
installing issue

### ISSUE THREAD

**Issue by bnj50** [brielin/Popcorn#15]
Dear author:
 we are getting this error when try to install the package in cluster unix (python 3.7)  (the older python - 2.7.15 is no longer compatible and throws a lot of errors). please advise, thanks!

Traceback (most recent call last): 
  File "/usr/local/python/3.7.1/bin/popcorn", line 11, in <module>
    load_entry_point('popcorn==0.9.9', 'console_scripts', 'popcorn')()
  File "/usr/local/python/3.7.1/lib/python3.7/site-packages/pkg_resources/__init__.py", line 481, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/python/3.7.1/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2694, in load_entry_point
    return ep.load()
  File "/usr/local/python/3.7.1/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2325, in load
    return self.resolve()
  File "/usr/local/python/3.7.1/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2331, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/python/3.7.1/lib/python3.7/site-packages/popcorn-0.9.9-py3.7.egg/popcorn/__main__.py", line 4, in <module>
    import fit
  File "/usr/local/python/3.7.1/lib/python3.7/site-packages/fit.py", line 302, in <module>
    @polN_dec
  File "/usr/local/python/3.7.1/lib/python3.7/site-packages/fit.py", line 284, in polN_dec
    degree = int(func.func_name.replace("pol",""))
AttributeError: 'function' object has no attribute 'func_name'

**Comment by brielin** [comment]
Hi,

Python 3 is not supported and at this time I dont have time to port it myself. You're welcome to try.

Thanks,
Brielin
