### ISSUE TITLE
No such file or directory: 'Popcorn/test/EUR_ref.bed.bim'

### ISSUE THREAD

**Issue by opain** [brielin/Popcorn#21]
Hello,

I am receiving the following error when using the test command:

#######################

(base) [k1806347@nodeb21 [rosalind] Software]$ ./popcorn.sh compute -v 2 --bfile1 Popcorn/test/EUR_ref --bfile2 Popcorn/test/EAS_ref --gen_effect Popcorn/test/EUR_EAS_test_ge.cscore
Popcorn version 1.0
(C) 2015-2019 Brielin C Brown
University of California, Berkeley
GNU General Public License v3

Invoking command: python /users/k1806347/brc_scratch/Software/Popcorn/popcorn/__main__.py compute -v 2 --bfile1 Popcorn/test/EUR_ref --bfile2 Popcorn/test/EAS_ref --gen_effect Popcorn/test/EUR_EAS_test_ge.cscore
Beginning analysis at Fri Feb  5 16:26:18 2021
Traceback (most recent call last):
  File "/users/k1806347/brc_scratch/Software/Popcorn/popcorn/__main__.py", line 248, in <module>
    main()
  File "/users/k1806347/brc_scratch/Software/Popcorn/popcorn/__main__.py", line 234, in main
    scores = compute.covariance_scores_2_pop(args)
  File "/mnt/lustre/users/k1806347/Software/Popcorn/popcorn/compute.py", line 228, in __init__
    names=['chm','id','pos_mb','pos_bp','a1','a2'])
  File "/users/k1806347/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 765, in read_table
    return read_csv(**locals())
  File "/users/k1806347/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 686, in read_csv
    return _read(filepath_or_buffer, kwds)
  File "/users/k1806347/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 452, in _read
    parser = TextFileReader(fp_or_buf, **kwds)
  File "/users/k1806347/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 946, in __init__
    self._make_engine(self.engine)
  File "/users/k1806347/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 1178, in _make_engine
    self._engine = CParserWrapper(self.f, **self.options)
  File "/users/k1806347/.local/lib/python3.7/site-packages/pandas/io/parsers.py", line 2008, in __init__
    self._reader = parsers.TextReader(src, **kwds)
  File "pandas/_libs/parsers.pyx", line 382, in pandas._libs.parsers.TextReader.__cinit__
  File "pandas/_libs/parsers.pyx", line 674, in pandas._libs.parsers.TextReader._setup_parser_source
FileNotFoundError: [Errno 2] No such file or directory: 'Popcorn/test/EUR_ref.bed.bim'
(base) [k1806347@nodeb21 [rosalind] Software]$ cd Popcorn/
(base) [k1806347@nodeb21 [rosalind] Popcorn]$ git pull
Already up-to-date.

###################

The error suggests it is looking for a file ending .bed.bim, which seems odd.

Do you have any advice on how to resolve this?

Many thanks,

Ollie

**Comment by opain** [comment]
Apologies, I have just seen on another issue that Python 3 is not supported. I have now run using Python 2 and the error no longer persists.
