### ISSUE TITLE
Runtime error

### ISSUE THREAD

**Issue by bethrusnak** [brielin/Popcorn#24]
# popcorn compute -h

Traceback (most recent call last):
  File "/usr/local/python/bin/popcorn", line 33, in <module>
    sys.exit(load_entry_point('popcorn==0.9.9', 'console_scripts', 'popcorn')())
  File "/usr/local/python/bin/popcorn", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/usr/local/python/lib/python3.9/importlib/metadata.py", line 77, in load
    module = import_module(match.group('module'))
  File "/usr/local/python/lib/python3.9/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 986, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 680, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 790, in exec_module
  File "<frozen importlib._bootstrap>", line 228, in _call_with_frames_removed
  File "/usr/local/python/lib/python3.9/site-packages/popcorn-0.9.9-py3.9.egg/popcorn/__main__.py", line 4, in <module>
    import fit
  File "/usr/local/python/lib/python3.9/site-packages/fit/__init__.py", line 53
    raise exc_type, exc_val, exc_tb
                  ^
SyntaxError: invalid syntax

**Comment by brielin** [comment]
This code is Python2 only.

**Comment by bethrusnak** [comment]
Thank you. I did not see that in the requirements.
