### ISSUE TITLE
numpy.float64' object cannot be interpreted as an integer

### ISSUE THREAD

**Issue by smuchakiel** [brielin/Popcorn#28]
Hi, I want to check two diseases on heritability and genetic correlation. 

##################################
Here is an example with my input datasets:
##################################

dataset1
SNP	A1	A2	N	beta	SE	P	OR	Z	AF
1:61743	C	G	538622	0.1163	0.0841	0.1664	1.12333	1.472	0.9981
dataset2
SNP	A1	A2	N	beta	SE	P	OR	Z	AF
1:10352	T	TA	106645	0.0327963	0.013999999999999999	0.019151.03334	-0.160	0.575901

####################
Sadly I received this error.
####################

Traceback (most recent call last):
  File "/home/mucha/POPCORN/popcorn/__main__.py", line 248, in <module>
    main()
  File "/home/mucha/POPCORN/popcorn/__main__.py", line 208, in main
    data = sumstats.sumstats_2_trait(scores,args)
  File "/home/mucha/POPCORN/popcorn/sumstats.py", line 193, in __init__
    if not data1['a1'][0].isupper():
  File "/home/mucha/anaconda3/lib/python3.7/site-packages/pandas/core/series.py", line 850, in __getitem__
    return self._values[key]
IndexError: index 0 is out of bounds for axis 0 with size 0
Traceback (most recent call last):
  File "/home/mucha/POPCORN/popcorn/__main__.py", line 248, in <module>
    main()
  File "/home/mucha/POPCORN/popcorn/__main__.py", line 220, in main
    res = fit.fit_pg(data.data,args,M=M)
  File "/home/mucha/POPCORN/popcorn/fit.py", line 243, in __init__
    self.jackknife = jackknife.jackknife(close_call,data,res,args)
  File "/home/mucha/POPCORN/popcorn/jackknife.py", line 17, in __init__
    self.blocks, self.bs = self.get_blocks(N,args)
  File "/home/mucha/POPCORN/popcorn/jackknife.py", line 33, in get_blocks
    A = np.floor(np.linspace(0,N,nblocks+1)).astype(int)
  File "<__array_function__ internals>", line 6, in linspace
  File "/home/mucha/anaconda3/lib/python3.7/site-packages/numpy/core/function_base.py", line 113, in linspace
    num = operator.index(num)
TypeError: 'numpy.float64' object cannot be interpreted as an integer

**Comment by smuchakiel** [comment]
I tried this also with the "test_dataset" EUR_test.txt, same error.
