### ISSUE TITLE
compute fails with "operands could not be broadcast together with shapes" error

### ISSUE THREAD

**Issue by ofrei** [brielin/Popcorn#36]
```
wget https://ctg.cncr.nl/software/MAGMA/ref_data/g1000_eas.zip --no-check-certificate && unzip g1000_eas.zip
wget https://ctg.cncr.nl/software/MAGMA/ref_data/g1000_eur.zip --no-check-certificate && unzip g1000_eur.zip 

popcorn compute --bfile1 g1000_eur --bfile2 g1000_eas g1000_eur_eas.cscore
```

led to 

```
Traceback (most recent call last):
  File "/usr/local/bin/popcorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.10/site-packages/popcorn/__main__.py", line 232, in main
    scores = compute.covariance_scores_2_pop(args)
  File "/usr/local/lib/python3.10/site-packages/popcorn/compute.py", line 328, in __init__
    self.scoresX = self.compute2(bed_1,bed_1_index,bed_2,bed_2_index,
  File "/usr/local/lib/python3.10/site-packages/popcorn/compute.py", line 484, in compute2
    _out2 = np.hstack((align_mat*out2,[[1]]))
ValueError: operands could not be broadcast together with shapes (1,9714) (1,0)
```

**Comment by ritah-nabunje** [comment]
Any solution to this? I have the same error and the `*.o.log` file has   
`Error when setting scores. Block width may exceed number of SNPs being stored Try increasing --SNPs_to_store
`

**Comment by ritah-nabunje** [comment]
> Any solution to this? I have the same error and the `*.o.log` file has `Error when setting scores. Block width may exceed number of SNPs being stored Try increasing --SNPs_to_store `


This closed issue helps help https://github.com/brielin/Popcorn/issues/12#issuecomment-627472180

**Comment by Taewoong-Ha** [comment]
> > Any solution to this? I have the same error and the `*.o.log` file has `Error when setting scores. Block width may exceed number of SNPs being stored Try increasing --SNPs_to_store `
> 
> This closed issue helps help [#12 (comment)](https://github.com/brielin/Popcorn/issues/12#issuecomment-627472180)


I have resolved this issue. However,
 I'm not entirely sure if it is correct. 
In the compute.py file, I modified the line from _out2 = np.hstack((align_mat*out2,[[1]])) to _out2 = np.hstack((align_mat * out2, np.array([[1]]))).

**Comment by bcbg-bio** [comment]
This seems to be drive by trying to access scores that couldn't be set due to the listed error message.

The latest version now exits after that prints. Try following the suggestion in the error message or removing the problematic region.
