### ISSUE TITLE
'AssertionError: Expect col to appear in data only once' in compute function

### ISSUE THREAD

**Issue by poppyzenzi** [brielin/Popcorn#41]
Hello

I received the same error as in the closed issue #14 but have confirmed no duplicate SNPs or individuals in the bfiles. Would you happen to have any suggestions?

I really appreciate any help you can provide. Thank you.

```80846148 Variants in file 1
80846148 Variants in file 2
4907928 SNPs in file 1 after MAF and indel filter
6856470 SNPs in file 2 after MAF and indel filter
3946796 SNPs common in both populations
Traceback (most recent call last):
  File "/exports/igmm/eddie/GenScotDepression/anaconda/envs/mypython/bin/popcorn", line 8, in <module>
    sys.exit(main())
  File "/exports/igmm/eddie/GenScotDepression/anaconda/envs/mypython/lib/python3.7/site-packages/popcorn/__main__.py", line 232, in main
    scores = compute.covariance_scores_2_pop(args)
  File "/exports/igmm/eddie/GenScotDepression/anaconda/envs/mypython/lib/python3.7/site-packages/popcorn/compute.py", line 286, in __init__
    bed_1_index = np.sort(bed_1.sid_to_index(snps_to_use)) #
  File "/exports/igmm/eddie/GenScotDepression/anaconda/envs/mypython/lib/python3.7/site-packages/pysnptools/snpreader/snpreader.py", line 520, in sid_to_index
    return self.col_to_index(list)
  File "/exports/igmm/eddie/GenScotDepression/anaconda/envs/mypython/lib/python3.7/site-packages/pysnptools/pstreader/pstreader.py", line 568, in col_to_index
    ), "Expect col to appear in data only once."
AssertionError: Expect col to appear in data only once.```

**Comment by poppyzenzi** [comment]
Issue was due to missing variant ids "."
