### ISSUE TITLE
AssertionError: Expect col to appear in data only once.

### ISSUE THREAD

**Issue by Tingwei1021** [brielin/Popcorn#42]
I am using the command `popcorn compute --bfile PATH_TO_PLINK_FILESET OUTPUT_RESULT` 
But I keep getting this error: 
`Traceback (most recent call last):
  File "/mnt/data_schen_1/anaconda3/envs/Popcorn/bin/popcorn", line 8, in <module>
    sys.exit(main())
  File "/mnt/data_schen_1/anaconda3/envs/Popcorn/lib/python3.7/site-packages/popcorn/__main__.py", line 227, in main
    scores = compute.covariance_scores_1_pop(args)
  File "/mnt/data_schen_1/anaconda3/envs/Popcorn/lib/python3.7/site-packages/popcorn/compute.py", line 62, in __init__
    bed_1_index = np.sort(bed_1.sid_to_index(snps_to_use)) #
  File "/mnt/data_schen_1/anaconda3/envs/Popcorn/lib/python3.7/site-packages/pysnptools/snpreader/snpreader.py", line 520, in sid_to_index
    return self.col_to_index(list)
  File "/mnt/data_schen_1/anaconda3/envs/Popcorn/lib/python3.7/site-packages/pysnptools/pstreader/pstreader.py", line 574, in col_to_index
    ), "Expect col to appear in data only once."
AssertionError: Expect col to appear in data only once.`  

I found out that the input was read incorrectly. This issue causes variants to be same(let's say 12:000012 reads as 12:00001, which duplicates with actual 12:00001)

**Comment by chirrie** [comment]
How did you solve the issue? I am also stuck there

**Comment by xEmz** [comment]
Same issue for me, too. But what did you change to fix the duplicate issue?

**Comment by bcbg-bio** [comment]
I can't replicate this issue. If you can provide me with an example plink fileset that I can use replicate it, I will look into it a bit.
