### ISSUE TITLE
np.bool deprecated in newer versions of NumPy

### ISSUE THREAD

**Issue by seanelizabethcaron** [brielin/Popcorn#43]
The following error is produced when running popcorn with NumPy >= 1.20.

Performing jackknife estimation of the standard error using 200 blocks of size 17925 .
/usr/local/lib/python3.8/dist-packages/popcorn/jackknife.py:44: FutureWarning: In the future `np.bool` will be defined as the corresponding NumPy scalar.
  k = np.ones((x.shape[0]),dtype=np.bool)
Traceback (most recent call last):
  File "/usr/local/bin/popcorn", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/dist-packages/popcorn/__main__.py", line 218, in main
    res = fit.fit_pg(data.data,args,M=M)
  File "/usr/local/lib/python3.8/dist-packages/popcorn/fit.py", line 241, in __init__
    self.jackknife = jackknife.jackknife(close_call,data,res,args)
  File "/usr/local/lib/python3.8/dist-packages/popcorn/jackknife.py", line 19, in __init__
    self.psuedovalues, self.delete_values = self.jackknife(f,x,r)
  File "/usr/local/lib/python3.8/dist-packages/popcorn/jackknife.py", line 44, in jackknife
    k = np.ones((x.shape[0]),dtype=np.bool)
  File "/usr/local/lib/python3.8/dist-packages/numpy/__init__.py", line 305, in __getattr__
    raise AttributeError(__former_attrs__[attr])
AttributeError: module 'numpy' has no attribute 'bool'.
`np.bool` was a deprecated alias for the builtin `bool`. To avoid this error in existing code, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations

Could you please update line 44 in jackknife.py to replace np.bool with np.bool_ such that this will run properly with newer NumPy without modification?

Thank you!

**Comment by seanelizabethcaron** [comment]
I was able to correct this in my environment by just modifying line 44 in
jackknife.py to use np.bool_ instead of np.bool. This sed command should do
the job:

sed -i -e 's/np.bool/np.bool_/'
/usr/local/lib/python3.8/dist-packages/popcorn/jackknife.py

It looks like maybe the change didn't stick for you (see line 5 in the
traceback - you still have np.bool and not np.bool_)? Perhaps you
accidentally reinstalled the library from Github again over your modified
version?

Best,

Sean

*Sean Caron (she/they)*
*OS Programmer Lead*
*University of Michigan Center for Statistical Genetics*
*Department of Biostatistics, School of Public Health*
*e: ***@***.*** ***@***.***> p: 734-474-5962*

**Comment by francontiram** [comment]
Thank you Sean – yes I realised popcorn was loading from local libs and when I changed the jackknife file there then the single change to np.bool_ worked for me too!

I deleted my comment as your fix did the job.

Thanks again,

Fran

**Comment by seanelizabethcaron** [comment]
Wonderful! I'm so happy that my issue report was able to help others!

Best,

Sean

*Sean Caron (she/they)*
*OS Programmer Lead*
*University of Michigan Center for Statistical Genetics*
*Department of Biostatistics, School of Public Health*
*e: ***@***.*** ***@***.***> p: 734-474-5962*

**Comment by bcbg-bio** [comment]
This change seems to have been rolled back in newer numpy? I don't see the warning using 2.2.4, and the latest docs have both np.bool and np.bool_. Will leave this and close for now, feel free to reopen if there is a need.
